language: java

env:
  global:
  - MAVEN_OPTS="-Xmx512M -XX:+ExitOnOutOfMemoryError"
  - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"
  - MAVEN_FAST_INSTALL="-DskipTests $MAVEN_SKIP_CHECKS_AND_DOCS -B -q -T C1"

install:
- mvn install $MAVEN_FAST_INSTALL

script:
- mvn test $MAVEN_SKIP_CHECKS_AND_DOCS -B
cache:
  directories:
  - $HOME/.m2/repository
